name: Delete GitHub Package

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Mag.Newtonsoft.Json from GitHub Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: Mag.Newtonsoft.Json
          package-type: nuget
          min-versions-to-keep: 0
